# ===================================================================
# 3. docker-compose.prod.yml (운영용 덮어쓰기 파일)
# - Jenkins 등 CI/CD를 통해 실제 서버에 배포할 때 사용합니다.
# ===================================================================
services:
  ai:
    restart: always
    volumes:
      - /home/ubuntu/data:/app/data
  backend:
    # 운영 환경에서는 기본 Dockerfile을 사용합니다.
    build:
      dockerfile: Dockerfile
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WS_URL=https://j13a101.p.ssafy.io/ws
    restart: always
    environment:
      - NEXT_PUBLIC_WS_URL=https://j13a101.p.ssafy.io/ws

  mysql:
    # 보안을 위해 운영 환경에서는 DB 포트를 외부에 노출하지 않습니다.
    restart: always

  redis:
    # 보안을 위해 운영 환경에서는 Redis 포트를 외부에 노출하지 않습니다.
    restart: always

networks:
  my-network:
    external: true
